/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw;
typedef struct tyObject_RefHeader__1FpxtYqBrM9cWvbcwDoGGwQ tyObject_RefHeader__1FpxtYqBrM9cWvbcwDoGGwQ;
typedef struct tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA;
typedef struct tyObject_ArithmeticDefect__CsIf5MISqzAz1sLsIDSHRg tyObject_ArithmeticDefect__CsIf5MISqzAz1sLsIDSHRg;
typedef struct tyObject_Defect__LVOh9ayYQ0Qgb1VqzuHGw4g tyObject_Defect__LVOh9ayYQ0Qgb1VqzuHGw4g;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__m9b0zXMpSmgmb6qL2RE0cag tySequence__m9b0zXMpSmgmb6qL2RE0cag;
typedef struct tySequence__m9b0zXMpSmgmb6qL2RE0cag_Content tySequence__m9b0zXMpSmgmb6qL2RE0cag_Content;
typedef struct tyObject_GcEnv__BQ2p5KQzLapExfZkj9b7Gig tyObject_GcEnv__BQ2p5KQzLapExfZkj9b7Gig;
typedef struct tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__v7uWnvec9cHpdQs2bKZ9bwKQ tyObject_CellSeq__v7uWnvec9cHpdQs2bKZ9bwKQ;
typedef struct tyTuple__ZxWaiNuCnHwtCFRAau5mfw tyTuple__ZxWaiNuCnHwtCFRAau5mfw;
typedef struct tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw;
typedef struct tyObject_StackTraceEntry__He8miiOGJYPIhYdkeY8HbA tyObject_StackTraceEntry__He8miiOGJYPIhYdkeY8HbA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__1FpxtYqBrM9cWvbcwDoGGwQ {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__m9b0zXMpSmgmb6qL2RE0cag {
  NI len; tySequence__m9b0zXMpSmgmb6qL2RE0cag_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__m9b0zXMpSmgmb6qL2RE0cag trace;
	Exception* up;
};
struct tyObject_Defect__LVOh9ayYQ0Qgb1VqzuHGw4g {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__CsIf5MISqzAz1sLsIDSHRg {
	tyObject_Defect__LVOh9ayYQ0Qgb1VqzuHGw4g Sup;
};
struct tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA {
	tyObject_ArithmeticDefect__CsIf5MISqzAz1sLsIDSHRg Sup;
};
struct tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__v7uWnvec9cHpdQs2bKZ9bwKQ {
	NI len;
	NI cap;
	tyTuple__ZxWaiNuCnHwtCFRAau5mfw* d;
};
struct tyObject_GcEnv__BQ2p5KQzLapExfZkj9b7Gig {
	tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ traceStack;
	tyObject_CellSeq__v7uWnvec9cHpdQs2bKZ9bwKQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw {
	tyObject_Defect__LVOh9ayYQ0Qgb1VqzuHGw4g Sup;
};
struct tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw {
	tyObject_Defect__LVOh9ayYQ0Qgb1VqzuHGw4g Sup;
};
struct tyObject_StackTraceEntry__He8miiOGJYPIhYdkeY8HbA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__m9b0zXMpSmgmb6qL2RE0cag_Content { NI cap; tyObject_StackTraceEntry__He8miiOGJYPIhYdkeY8HbA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4691)(tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3464)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__1FpxtYqBrM9cWvbcwDoGGwQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5164)(tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u74)(tySequence__m9b0zXMpSmgmb6qL2RE0cag dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5176)(tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3004)(tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3012)(tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4703)(tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4760)(tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4772)(tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__YI7187pmjrb8bdES7qx6fw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__TOItSlB6Fje3ODy0SAYVZA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__9czGM4lETiJfsBUX7UP5npw_;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[5] = {3701606400, 1285336064, 1403123456, 3256869888, 3794618880};
N_LIB_PRIVATE TNimTypeV2 NTIv2__TOItSlB6Fje3ODy0SAYVZA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___system_u5176, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 1403123456, 2398483200};
N_LIB_PRIVATE TNimTypeV2 NTIv2__YI7187pmjrb8bdES7qx6fw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u4703, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 1403123456, 831316480};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9czGM4lETiJfsBUX7UP5npw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)eqtrace___system_u4772, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/arithmetics.nim");
	nimlf_(364, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5164)(tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5164(((tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/arithmetics.nim");
	nimln_(353);	nimln_(357);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3004)(tyObject_CellSeq__UVTFANOdqNzm0tNolwjWBQ* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3012(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/orc.nim");
	nimlf_(138, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__BQ2p5KQzLapExfZkj9b7Gig* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__BQ2p5KQzLapExfZkj9b7Gig*) (env_p1));
		nimln_(141);		add__system_u3004((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5176)(tyObject_OverflowDefect__TOItSlB6Fje3ODy0SAYVZA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__1FpxtYqBrM9cWvbcwDoGGwQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__1FpxtYqBrM9cWvbcwDoGGwQ*) (T5_));
		nimlf_(521, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3464(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4691)(tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4691(((tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4703)(tyObject_RangeDefect__YI7187pmjrb8bdES7qx6fw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4760)(tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4760(((tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4772)(tyObject_IndexDefect__9czGM4lETiJfsBUX7UP5npw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
