/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1) {
	nimfr_("addInt", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/std/private/digitsutils.nim");
	nimlf_(116, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/std/private/digitsutils.nim");	addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64) (x_p1)));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0) {
	NimStringV2 result;
	nimfr_("$", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/dollars.nim");
	nimlf_(20, "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_4;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), xX60gensym0__p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0) {
	NimStringV2 result;
	nimfr_("$", "/opt/homebrew/Cellar/nim/2.2.6/nim/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u187((&result), xX60gensym4__p0);
	popFrame();
	return result;
}
